Migrated (hopefully seamless) to new Spring boot version
starwit/reacthook-spring-template pull request #28
Opened 2023-07-15 19:29 UTC by DerCed

2023-07-15 22:09 UTC, DerCed commented
Sadly, I could not test the Postgres variant. The normal variant did work however, as expected.

2023-08-03 10:45 UTC, witchpou requested changes

2023-08-03 10:45 UTC, witchpou commented on generator-templates/application/properties.ftl
> +# Authentication
das geht so nicht. Bitte schaue dir die changes bzgl. dev-mode an

2023-08-06 21:31 UTC, DerCed commented
@witchpou Approved via Teams message

2023-08-06 21:31 UTC, merged