Added theme and fixed indent
starwit/reacthook-spring-template pull request #6
Opened 2022-05-28 15:26 UTC by DerCed

2022-06-08 08:26 UTC, witchpou reviewed
abgesehen davon, dass ich eigentlich erwartet habe, dass sich grundsätzlich bzgl. Styles nur zwei Dateien ändern und dann evtl. noch indent Sachen, sieht es von der Idee her gut aus. Lass uns aber erst einmal die anderen Sachen integrieren.

2022-06-08 08:30 UTC, witchpou reviewed
ich kann mir nicht vorstellen, dass der indent jetzt überall gleich ist. Aber lass uns das erst einmal so lassen und die anderen Sachen integrieren.

2022-06-08 08:33 UTC, DerCed commented
Überall wo stack genutzt wird im standard schon. Ich war der Meinung, dass das soweit überall geschehen ist. Ich hoffe, dass ich nichts übersehen habe

2022-06-17 20:49 UTC, witchpou reviewed
Ein paar von den Sachen müssen noch ins Template. Theme und Header würde ich aber hier drin lassen...ich mache dazu morgen noch einen PR für react-starwit.

2022-06-17 20:49 UTC, witchpou commented on reacthookspring/webclient/app/src/app/assets/themes/MainTheme.jsx
> +import ComponentTheme from "../../assets/themes/ComponentTheme";
Abgesehen davon, dass ich nicht glaube, dass das so funktioniert. Wieso ist die MainTheme.jsx in die Assets gewandert. Was ist der Unterschied zum AppHeader.jsx. Mich würden einfach die Gedanken dahinter interessieren

2022-06-18 09:20 UTC, witchpou requested changes
Die Dateien, die ich nach react-starwit übertragen habe, müssen hier noch gelöscht werden. Der eine Import im MainTheme.jsx sieht noch merkwürdig aus. Das andere sind Anmerkungen

2022-06-18 09:20 UTC, witchpou commented on reacthookspring/webclient/app/src/app/commons/buttons/addFabButton/AddFabButton.jsx
Änderungen übertragen auf react-starwit Branch feature/AB#248-Create_standardized. Hier bitte löschen.

2022-06-18 09:20 UTC, witchpou commented on reacthookspring/webclient/app/src/app/commons/buttons/gitDownloadButton/GitDataButton.jsx
>      return (
Änderungen übertragen auf react-starwit Branch feature/AB#248-Create_standardized. Hier bitte löschen.

2022-06-18 09:20 UTC, witchpou commented on reacthookspring/webclient/app/src/app/commons/form/EntityDetail.jsx
>          <Container>
Änderungen übertragen auf react-starwit Branch feature/AB#248-Create_standardized. Hier bitte löschen.

2022-06-18 09:22 UTC, witchpou requested changes
Und bitte auch in Project react-starwit und den glechnamigen Branch testen, ob die Button-Farbe im ProjectBuilder noch so ist wie vorher.

2022-06-18 10:59 UTC, DerCed commented
Warte, was soll jetzt hier wie getan werden? Das ist wie besprochen ein anderes Farb-Theme als im ProjectBuilder. Also die Buttonfarben sind anders. Soll ich das Theming noch übertragen oder hast du das jetzt schon gemacht?

2022-06-20 18:50 UTC, witchpou approved these changes

2022-06-20 18:51 UTC, merged