add enum to entity
starwit/reacthook-spring-template pull request #8
Opened 2022-06-01 08:44 UTC by witchpou

2022-06-18 10:00 UTC, witchpou reviewed
@DerCed: bitte reviewen. Wenn dir integrations-PR gemerged ist, kann ich dann noch die Dateien die ich in commons geändert hab, löschen.

2022-06-19 10:44 UTC, DerCed requested changes
Sorry für das späte Review. Passt für mich - Wie im anderen PR angemerkt: Es fehlt das doppelte === bez der Typensicherheit

2022-06-19 10:44 UTC, DerCed commented on reacthookspring/webclient/app/src/app/commons/form/EntityDetail.jsx
> +                        } else if (isEnum(field.type)) {
Die einzelnen return values müssen noch in seperate Funktionen ausgelagert werden (für das nächste refactoring)

2022-06-19 10:44 UTC, DerCed commented on reacthookspring/webclient/app/src/app/commons/inputFields/validatedTextField/ValidatedTextField.jsx
> +        if (!!max && type != "string" && value > max) {
!== statt !=

2022-06-19 10:44 UTC, DerCed commented on reacthookspring/webclient/app/src/app/modifiers/DefaultModifier.js
> +    fieldType == "long";
=== statt ==

2022-06-19 10:44 UTC, DerCed commented on reacthookspring/webclient/app/src/app/modifiers/DefaultModifier.js
> +                if (draft[field.name]?.id == -1 || draft[field.name] == "") {
=== statt ==

2022-06-19 10:44 UTC, DerCed commented on reacthookspring/webclient/app/src/app/modifiers/DefaultModifier.js
> +                if (draft[field.name] == "") {
```suggestion
                if (draft[field.name] === "") {
```

2022-06-19 10:44 UTC, DerCed commented on reacthookspring/webclient/app/src/app/modifiers/DefaultModifier.js
> +                if (draft[field.name]?.id == -1 || draft[field.name] == "") {
```suggestion
                if (draft[field.name]?.id === -1 || draft[field.name] === "") {
```

2022-06-19 10:44 UTC, DerCed commented on reacthookspring/webclient/app/src/app/modifiers/DefaultModifier.js
> +    fieldType == "long";
```suggestion
    return fieldType === "integer" ||
    fieldType === "bigdecimal" ||
    fieldType === "float" ||
    fieldType === "doulbe" ||
    fieldType === "long";
```

2022-06-19 10:44 UTC, DerCed commented on reacthookspring/webclient/app/src/app/modifiers/DefaultModifier.js
>          fieldType == "integer" ||
Weil es mir hier auch gerade auffällt: ===

2022-06-19 10:44 UTC, DerCed commented on reacthookspring/webclient/app/src/app/commons/inputFields/validatedTextField/ValidatedTextField.jsx
> +        if (!!max && type != "string" && value > max) {
```suggestion
        if (!!max && type !== "string" && value > max) {
```

2022-06-19 10:44 UTC, DerCed commented on reacthookspring/webclient/app/src/app/commons/inputFields/validatedTextField/ValidatedTextField.jsx
> +        if (!!min && type != "string" && value < min) {
```suggestion
        if (!!min && type !== "string" && value < min) {
```

2022-06-20 18:36 UTC, DerCed approved these changes

2022-06-20 18:36 UTC, merged